[package]
name = "color-cut"
version = "0.1.0"
authors = ["Florian Hars <florian@hars.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vte = "0.10"
unicode-width = "0.1.7"
clap = "2.33"
